server:
  port: 9999
  contextPath: /uaa
logging:
  level:
    org.springframework.security: DEBUG
spring:
  application:
    name: authservice

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
