#Default port is 8761 server:
server:
  port: 5555
management:
  security:
    enabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignore-services: service-two
  routes:
    service-two: /servicetwo/**
