#Default port is 8761 server:
server:
  port: 5555
management:
  security:
    enabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignore-services: '*'
  prefix: /api
  routes:
    service-two: /servicetwo/**
    service-one: #Ejemplo de roteo estatico
      path: /serviceone/**
      url: http://localhost:8080
