#Default port is 5555 server:
#Para refrescar la configuracion en caliente, hay que hacer un POST a /refresh
server:
  port: 5555
management:
  security:
    enabled: false
spring:
  application:
    name: apigateway
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix: # Configuro timeout para que no rompa si un servicio tarda mucho
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
zuul:
  sensitiveHeader: Cookie,Set-Cookie #Es una lista negra, al no estar Authorization, le estoy diciendo que propague el header
  ignore-services: '*'
  debug:
    request: true
  routes:
    service-two: /api/servicetwo/**
    service-three: /api/servicethree/**
    authservice: /auth/**
    #service-one: #Ejemplo de roteo estatico
      #path: /serviceone/**
      #url: http://localhost:8080
    #service-zero:
      #path: /servicezero/**
      #serviceId: servicezero
#ribbon: ejemplo de ruteo manual con multiples instancias
  #eureka:
    #enabled: false
#servicezero:
  #ribbon:
    #listOfServers: http://localhost:8086, http://localhost:8087
