server:
  port: 8888
spring:
  application:
    name: configuration-service
  cloud:
    config:
      enable: true
      server:
        git:
          uri: git@github.com:LaMaldicionDeMandos/test-spring-cloud-config-repo/
          searchPaths: service-one
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/