spring:
  application:
    name: service-one
  cloud:
    config:
      uri: http://localhost:8888
  stream:
    bindings:
      output:
        destination: exampleTopic #Nombre de la cola o topic
        content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost